### ISSUE TITLE
JCP - Joystream Tutorial Video Series

### ISSUE THREAD

**Issue by blrhc** [Joystream/bounties#18]
# Joystream Tutorial Video Series

_Relevant OKR: [Expand Joystream platform awareness](https://github.com/Joystream/joystream/tree/master/okrs#objective-expand-joystream-brand-awareness)_

### Problem
Joystream has 176 registered members, but hardly any serious engagement with the platform, as measured by video uploads, forum posts, and the number of typical applicants for the council during every cycle.

This is almost certainly in part due to a lack of understanding of how to get set up on the platform and how to perform roles. The helpdesk repository is a good start, but it's not very well publicised and is quite text heavy.

My proposed solution is a series of beginner friendly videos showing people how to do some of the simpler stuff on Joystream. These videos would also serve as some of the first "original content" on the Joystream platform, and the real engagement they will receive (both in and of themselves and for the platform) will hopefully provide useful data on how Joystream might be most effectively improved for its users.

Producing a couple of informational videos explaining what the aims of the Joystream project are (aside from the tutorials) might also be very useful in contributing towards the OKR mentioned above.

### Goals

- Produce visually appealing and easy to understand videos showing users how to use Joystream and perform some of the current roles.
- Produce a couple of informational videos about Joystream's mission.
- Attract more users to the platform by presenting the project as keen to obtain users with any technical ability level.
- Highlight enthusiastically within the videos the current benefits of being an early user of Joystream (i.e. XMR) and learning how it works.
- If possible, upload informational videos to Joystream's social media accounts.

**Comment by bwhm** [comment]
Hey @blrhc 
This is a very good idea IMO, and your first video was a great start.

> Produce visually appealing and easy to understand videos showing users how to use Joystream and perform some of the current roles.

This seems like the best place to start for me.

> Produce a couple of informational videos about Joystream's mission.

This is something we would really like to address, but it's also been on our agenda for a while to produce something professional...

I will try to setup a bounty for this before I go on holiday this Friday.
