### ISSUE TITLE
Bounty #3 - Compile list of free media and metadata sources - $* (Under Review)

### ISSUE THREAD

**Issue by bwhm** [Joystream/bounties#20]
#### Problem
We need sources of free and available media content, in various formats, in the following top level categories:
- video
- audio
- e-books

#### Goals

The goal of this bounty is twofold:

1. To get more content on the platform, and for stress tests of the storage and distribution system, we need to compile a list of freely available on demand media.

2. We are trying to build and adaptable and dynamic content directory system for our next testnet, `Rome`. The specs are still a WIP, but the general concept is discussed [here](https://github.com/Joystream/joystream/issues/74). For the initial implementation, we want to learn more about what metadata is typically associated with each type of media, and how it's structured.

Using audio as an example:
What are the most important and relevant metadata for:
- Songs
- Albums
- Audiobooks
- Podcasts

#### Rewards

Each contribution will be evaluated on an individual basis, but we will assign a budget of $200 for the bounty.

#### Scope of Work

Search the web for sites or other platform containing freely available media content.

#### Deliverables

- Provide links to websites or other media platform containing "large" amounts of media content (video, audio, e-books).
- Include as much information as possible about the:
  - Type of content, if applicable (eg. video documentaries only)
  - Licensing restrictions (if the site contains a mix of content with different restrictions)

Any information about the following will add value, and thus increase the reward.
- How to download the files and metadata in bulk
- Any additional information that addresses `2.`

#### Constraints

- All submissions must be in line with our [ToS](https://testnet.joystream.org/acropolis/pioneer/#/pages/tos) to be evaluated.

#### Bounty format

Open for all.

#### Deadline

Unless we are satisfied before this time, the submission deadline is the 18th of August 2019. 

In case of the former, this section will be updated, but leaving 24hr for stragglers to submit.

**Comment by bwhm** [comment]
Please review @bedeho 
Remove "Draft" and merge upcoming PR unless you want to make some changes.

**Comment by kamalzaman** [comment]
Hi, some questions about the bounty.
What exactly is `metadata` in this bounty? 
So, the work result is a list of websites providing the media?
Given the nature of the task maybe the bounty is not only for one applicant?

**Comment by bwhm** [comment]
> What exactly is `metadata` in this bounty?

Metadata is the is information about the media file. Description of content, playtime year of recording, genre, etc...

The point is that a public domain movie would typically have some differences in the metadata than say, a podcast about crypto governance :) 

The former would maybe focus more on the director, actors, awards and synopsis.
The latter would be more focused on topics and guests.

> So, the work result is a list of websites providing the media?

Yes. Just a link is a start, but the more research you have done (eg. ensuring there's no licensing/copyright/policy infringements, type of content, quality of media, how to download in bulk, etc.), the more value you provide!

> Given the nature of the task maybe the bounty is not only for one applicant/worker?

It is not! It's open to all. The budget is at least $200, which we will distribute based on quality of work. This _may_ go up if we are overwhelmed by the quality and quantity, but not down :)

**Comment by blrhc** [comment]
# Freely Available Content
_Ben Holden-Crowther_

Based on my experience, the most powerful license to use in this instance would be the Public Domain (CC0) License. It means there's no attribution required and that Joystream et al. can do basically anything with the files downloaded.

## Sources
The sources below allow downloads from their public domain archives. There are clearly many other sources of "free" content, though often they have complicated licenses or a pretty poor selection of content. I have identified here my favourite sources for media content based on my own experience in this area.

### Video

- [Prelinger Archives](https://archive.org/details/prelinger) (1000's of archive videos including old movies and cartoons)
- [Wikimedia Commons](https://commons.wikimedia.org/wiki/Main_Page) (not very easy to search, though quite a lot of content available)
- US Government:  [Nasa](https://images.nasa.gov/), [National Parks Service](https://www.nps.gov/grca/learn/photosmultimedia/b-roll_hd_index.htm), etc.

### Audio

- [Musopen.org](https://musopen.org/) (Sheet music and performances of music in public domain)
- [Librivox](https://librivox.org/) (Public domain recordings of public domain works)
- [Open Goldberg Variations](https://www.opengoldbergvariations.org/) (Bach recordings)
- [Wikimedia Commons](https://commons.wikimedia.org/wiki/Main_Page) (not very easy to search, though quite a lot of content there)

### E-Books

- [Project Gutenberg](https://www.gutenberg.org/) (Enormous database of out-of-copyright works)
- [Europeana](https://www.europeana.eu/portal/en) (A smaller but also useful collection)
- US Government (e.g. [CIA World Factbook is public domain](https://www.cia.gov/library/publications/download))

## How To Download Files And Metadata In Bulk

This will probably not be an easy task. Many of these websites are designed in a way that prevents frictionless cloning of their databases from taking place. It would be possible to download the files using some sort of crawler bot/script. 

Unfortunately though, as far as I can see there is no easy solution to this that would not involve passively crawling these websites.

## Important Metadata For Different Media Types

### Video

Movies: `title, subtitle, genre, country of origin, original language, publication date [by different locations], director, screenwriter, cast members, director of photography, film editor, composer, producer, production company, distributor, theme music, narrative location, duration, aspect ratio, color, box office takings, budget, follows, followed by, ICAA rating, MPAA rating, IMDb ID.`

Episode of TV Series: `title, part of the series, season, original network, country of origin, original language, publication date, director, screenwriter, follows, followed by, production code, IMDb ID`

Music Video: `based on, director, cast members, color, part of, named after, title, genre, performer, record label, publication date, composer, lyrics by, followed by, follows, instrument, distribution format`

### Audio

Radio Programme: `inception, country, presenter, original network, language, producer, distrbution format, official website, web feed URL`

Podcasts: `genre, presenter, language, number of episodes, inception, distribution format, official website, IMDb ID`

Songs: `part of, named after, title, genre, performer, record label, publication date, composer, lyrics by, followed by, follows, instrument, distribution format`

Albums: `genre, performer, record label, language, publication date, follows, followed by`

Audiobooks: `edition of translation of, publisher, language of work, publication date, narrator, author, duration`

### E-books

Books: `title, derivative works, main subject, genre, editions, author, publisher, country of origin, language of work, publication date, narrator, narrative location, characters, follows, followed by, copyright status, set in period, Dewey Decimal Classification`

**Comment by blrhc** [comment]
Hope the above is helpful. I'll try to add some more sources here and more metadata if I can find it.

**Comment by bwhm** [comment]
Thanks @blrhc 
Will start reviewing as we get closer to "end" date and/or more contributions come in!

**Comment by finnyfound** [comment]
Hi @bwhm 

Here's something i found out.

**Video Sources**
Movie : http://publicdomainmovie.net
Includes : Feature Films, Comedy, Drama & Romance, Science Fiction,  Horror, Cartoons
Direct download available / Bulk download not available 
Each page will have metadatas like : Genre, Cast, Plot, Movie Name

Direct download link available / Bulk download not available
Bulk download available with file grabber tools like uget(linux) idm (windows)


**Audio Sources**
Music  : https://freepd.com/
Includes : UPBEAT , POSITIVE, MOTIVATIONAL , EPIC, DRAMATIC, HORROR , ROMANTIC , SENTIMENTAL, COMEDY, WORLD, PERCUSSION, UNDERSCORING, ELECTRONIC, MISCELLANEOUS 
Direct download available / Bulk download available if we donate
Each audio will have metadatas like : Genre, Artist, Song Name, License information 
Bulk download available with file grabber tools like uget(linux) idm (windows)

**Ebook Sources**
http://www.feedbooks.com/publicdomain

Each page will have metadetas like Title, Author, Category, Language

Direct download link available / Bulk download not available
Bulk download available with file grabber tools like uget(linux) idm (windows)

https://standardebooks.org/ebooks/

Each page will have metadetas like Title, Author, Category, Language

Direct download link available / Bulk download not available
Bulk download available with file grabber tools like uget(linux) idm (windows)


https://freekidsbooks.org/public/
kids book

Each page will have metadetas like Title, Author, Category, Language

Direct download link available / Bulk download not available
Foreign Language available
Bulk download available with file grabber tools like uget(linux) idm (windows)


##Meta Data Information
**Songs** - Artist , Album , Year , Track Number, Genre, Album Artist, Contributing Artist, Composers , Rating, Recorded Label, Album Image
Albums - 
**Audiobooks** - Artist, ALbum, Orginally Available , Rating, Recorded Label, Review,
Genre, Album Image,
**Podcasts -** 
Title – The podcast or episode title and number.
Artist – The artist or host.
Album – The title of the podcast.
Track – Your episode number, this will help sort episodes chronologically.
Year – The year published.
Genre – The genre.
Copyright – Copyright information.
Album Art – Album or cover art.
Comment – A short summary of your episode, you may add keywords.
URL – The website address for the podcast.


**Ebook - epub2/epub3**

Title: the book’s title
Language: the language that the book is in
Author: the author’s name or multiple authors’ names if a group project/anthology
Unique Identifier: this can be a Universally Unique Identifier or an ISBN; more details on uniquely identify an eBook here
The following metadata is optional, but strongly encouraged to be used in all eBook editions to accurately describe the book:

Publication Date: the date that the eBook was created
Publisher: the name of the publisher or the author’s name if independently published
Contributors: this includes the editor, cover artists, book designer, and many more; a complete list of contributors that can be listed is provided by the Library of Congress
Rights: a copyright notice; more on copyright here 
Description: a blurb about the book; if no blurb is available, the description can be something like The Wizard of Oz: A Novel
Keywords: these can be the same as what you type in at the eBook vendors (seven keywords is a good rule of thumb); you can also pick and choose from the predefined BISAC Subject Headings to make things easy (e.g. Fiction/Romance/Erotica)

Hope this helps.

**Comment by bwhm** [comment]
Thanks @finnyfound 
As stated earlier:
> Will start reviewing as we get closer to "end" date and/or more contributions come in!

**Comment by bwhm** [comment]
This bounty is now under review, and we cannot guarantee any new submissions will be considered.

**Comment by bwhm** [comment]
After reviewing this, I have decided to allocate 75% of the bounty bundget to @blrhc, and 25% to @finnyfound. This is to reflect my impression of the overall difference in quality and quantity of available media content, and its metadata.

Thanks again to both of you! 
Please provide XMR address for payments.

**Comment by blrhc** [comment]
Thank you very much! My XMR address is 48E7bfe5ugnRY2G5akDyd3XQUM9NdqRKRcHSfyNMVtJSFuJt6KvowVZNqGL5CWUeewchmxS7nvHHGfhSLgRvyHJmLEsyvTr.

**Comment by finnyfound** [comment]
Thank you, Here is my XMR address.
477A5x8NApy2eJRRZGV95RimgUMRY3KjFcJhc4TDbR8gHN5dThxShfC5ABwJhsXgSZ4aJzyNvzTWL3cSF9nUBy3iAUivawe

**Comment by bwhm** [comment]
@blrhc @finnyfound finally sent...
:)
