### ISSUE TITLE
Bounty #0 - Fix broken links, formatting, etc in READMEs - $2/fix

### ISSUE THREAD

**Issue by bwhm** [Joystream/bounties#3]
#### Problem

As the non-code repos are updated, it's difficult to avoid introducing broken links, errors with images, grammar mistakes, formatting errors, etc. This makes it difficult to navigate, and adds friction for readers. Note that this applies to ALL the README.md files, not just the top level one.

#### Goals

Improve quality and accessibility of our repos.

#### Rewards

$2 per fix that gets merged.

*Substantial improvements may be rewarded extra.*

#### Scope of Work & Deliverables

Fork the repo, and fix what is broken. Then make a PR in the applicable repo, and refer to it a reply answer in this issue.

Applicable repos are:
- https://github.com/Joystream/joystream
- https://github.com/Joystream/helpdesk
- https://github.com/Joystream/communications
- https://github.com/Joystream/bounties
- https://github.com/Joystream/design

#### Constraints

1. Although suggestions for clarifications, improvements, etc. are always welcome, please add them as comments instead of including them in the PR itself, to make the PR easier to review. If the reviewer agrees with your suggestion, you can add a new commit to the PR.

2. All links within the same repo must be relative instead of absolute. Example:

```
# From https://github.com/Joystream/joystream/tree/master/testnets/acropolis
# You want to link to: https://github.com/Joystream/joystream/tree/master/meetings/acropolis#launch-meeting
# Do this:
[link](../../meetings/acropolis/#launch-meeting)
# Not this:
[link](https://github.com/Joystream/joystream/tree/master/meetings/acropolis#launch-meeting)
```

3. When you start working, feel free to make a draft PR to show your intent, but preferably check the entire repo before
Preferably go through *all* the links before marking it ready for review, and assigning someone to review your.

*Update - 05.08.19*

4. Please use US English spelling for consistency across the organization.

5. Ideally, use [atom](https://atom.io/) as your editor, and add the following plugins:
- [markdown-preview-enhanced](https://atom.io/packages/markdown-preview-enhanced)
- [markdown-toc-auto](https://atom.io/packages/markdown-toc-auto)

To ensure it renders correctly.

#### Bounty format

First come first serve. Pay out on delivery.
For our convenience, add a comment and link to the PR in this issue, with number of fixes and expected payouts.

#### Deadline

Will most likely be kept open for years. Will honor contributions 48h after closing.

**Comment by emmaodia** [comment]
https://github.com/Joystream/helpdesk/pull/31
Update made to the configure your validator keys for Linux section of the Readme.
@bwhm

**Comment by bwhm** [comment]
> [Joystream/helpdesk#31](https://github.com/Joystream/helpdesk/pull/31)
> Update made to the configure your validator keys for Linux section of the Readme.
> @bwhm

Thanks for your contribution @emmaodia, paying out now!

**Comment by blrhc** [comment]
https://github.com/Joystream/joystream/pull/79
Am going to do some grammar checks on the other four repositories so will add my XMR address later.

**Comment by blrhc** [comment]
Have done the same with the other four qualifying repos:

https://github.com/Joystream/helpdesk/pull/36
https://github.com/Joystream/communications/pull/30
https://github.com/Joystream/bounties/pull/16 (in this repository)
https://github.com/Joystream/design/pull/11

XMR Address: 48E7bfe5ugnRY2G5akDyd3XQUM9NdqRKRcHSfyNMVtJSFuJt6KvowVZNqGL5CWUeewchmxS7nvHHGfhSLgRvyHJmLEsyvTr

**Comment by bwhm** [comment]
Tyvm @blrhc 
Will review and payout Monday at the latest.

**Comment by bwhm** [comment]
@blrhc 
Reviewed and merged. I counted 11 corrections, sending $22 your way :)

**Comment by blrhc** [comment]
> @blrhc
> Reviewed and merged. I counted 11 corrections, sending $22 your way :)

Thanks!

**Comment by blrhc** [comment]
Am including this one here for reference until it gets merged: https://github.com/Joystream/joystream/pull/81

Also, I wanted to state here that I am planning to do some similar fixes on the https://github.com/Joystream/design repository as there don't seem to be any pending pull requests in that repository and there's only one README.

I subsequently hope to make detailed corrections to the READMEs of the other qualifying repositories, and will state my intention here when I'm about to do so.

**Comment by blrhc** [comment]
https://github.com/Joystream/design/pull/12

**Comment by blrhc** [comment]
I am now planning to work on a detailed spelling, grammar and formatting review of https://github.com/Joystream/bounties

**Comment by blrhc** [comment]
Completed spelling, grammar and formatting review in this repository (https://github.com/Joystream/bounties/pull/19).

**Comment by bwhm** [comment]
> Completed spelling, grammar and formatting review in this repository (#19).

Merged!
Do you mind if we wait and add the WIP one before I pay?

**Comment by blrhc** [comment]
> > Completed spelling, grammar and formatting review in this repository (#19).
> 
> Merged!
> Do you mind if we wait and add the WIP one before I pay?

Absolutely no problem! I may end up doing a formatting check on https://github.com/Joystream/communications/ tomorrow anyway, so there's definitely no rush!

**Comment by blrhc** [comment]
Also noticed this one has been approved but not merged? https://github.com/Joystream/communications/pull/30

**Comment by kek-mex** [comment]
Hey. I submitted this: [Joystream/helpdesk#38](https://github.com/Joystream/helpdesk/pull/38)
Here is my XMR address: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by kek-mex** [comment]
Im going to look through the bounties readme.md, if i can find anything to do there.

**Comment by bwhm** [comment]
@kek-mex 
Sent! Thanks again for your contribution :)

**Comment by kek-mex** [comment]
Sorry. Forgot to mention that im going to do a PR (Pull Request) on the bounties README.md soon. There is no any open PR's, so i guess that no damage was made :)

**Comment by kek-mex** [comment]
I did create the next PR: [https://github.com/Joystream/bounties/pull/23](Joystream/bounties#23).
My XMR address for the bounty is:  47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by kek-mex** [comment]
I did create the next PR: [https://github.com/Joystream/bounties/pull/23](Joystream/bounties#23)  I think that there are 10 fixes that should be merged/paid

My XMR address for the bounty is:  47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by kek-mex** [comment]
Im looking to fix some typos on the "communications" repo, and creating a PR for them.

**Comment by kek-mex** [comment]
Fixed a few typos on [Joystream/bounties#31](https://github.com/Joystream/communications/pull/31/)
I count 3 typo's, that should be eligible for a reward.
XMR address: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by bwhm** [comment]
> Fixed a few typos on Joystream/bounties#31
I count 3 typo's, that should be eligible for a reward.

Thanks @kek-mex! Sending ASAP!

**Comment by blrhc** [comment]
Am putting this one here now that it has been merged: https://github.com/Joystream/joystream/pull/81/

I count 40 significant edits in total (plus $10 bonus).

XMR Address: 48E7bfe5ugnRY2G5akDyd3XQUM9NdqRKRcHSfyNMVtJSFuJt6KvowVZNqGL5CWUeewchmxS7nvHHGfhSLgRvyHJmLEsyvTr

**Comment by bwhm** [comment]
@blrhc 
Paid!

**Comment by blrhc** [comment]
Thanks :)

**Comment by blrhc** [comment]
![evaluateing](https://user-images.githubusercontent.com/4144334/63038161-307e7600-be86-11e9-9a8a-bcd046a28c78.jpeg)
Not in a README, but it is a spelling mistake (evaluateing vs evaluating).

**Comment by blrhc** [comment]
The helpdesk review I did here (https://github.com/Joystream/helpdesk/pull/39/) made 45 significant corrections overall.

XMR Address: 48E7bfe5ugnRY2G5akDyd3XQUM9NdqRKRcHSfyNMVtJSFuJt6KvowVZNqGL5CWUeewchmxS7nvHHGfhSLgRvyHJmLEsyvTr

**Comment by blrhc** [comment]
@bwhm I've noticed quite a few spelling/grammar mistakes in the Joystream.org website too. Is there any chance the scope of this bounty might be widened to include the website in the future?

**Comment by bwhm** [comment]
> ... Is there any chance the scope of this bounty might be widened to include the website in the future?

It will be included unofficially :)

Paying out 47*$2 tomorrow morning!

**Comment by kek-mex** [comment]
I found something to fix on the Joystream/helpdesk repo, so im going to see if i can find anything else to fix.

**Comment by kek-mex** [comment]
Made some improvements here: [Joystream/bounties#40](https://github.com/Joystream/helpdesk/pull/40)
I did count around 8 improvements, that should be worth of the reward.
XMR address: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by kek-mex** [comment]
I have some fixes to the "Joystream/joystream" repo, and i will create a draft PR for that.

**Comment by bwhm** [comment]
> I did count around 7 improvements, that should be worth of the reward.

Thanks, sending!

**Comment by kek-mex** [comment]
I did submit a new PR [Joystream/joystream#111](https://github.com/Joystream/joystream/pull/111/).
I know it has not been closed yet, but I figured out, that I'd post here now. I think that 7 changes should be rewarded.
As always, my XMR address is the following: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

Ps. There is a typo on the description of the Joystream/Design repo, as you can see from below:
![Screenshot_20190829_204653](https://user-images.githubusercontent.com/50080006/63963982-c6c5b500-ca9e-11e9-8d84-c1cc6ffcdbc2.png)

**Comment by bwhm** [comment]
Thanks @kek-mex, transfer made!

**Comment by goodship1** [comment]
Is this still open ?

**Comment by bwhm** [comment]
> Is this still open ?

Yessir!

**Comment by koen84** [comment]
I submitted [https://github.com/Joystream/helpdesk/pull/42](url) to note no open incoming ports are required for running a validator.

XMR address :  85pmK15VYrjV4ovpc3uRoc2rthkHxKB2n9aAAEt2r6ZzdfD9daC5RiDB5iVSxnmtbzjUtCdw5wjpVhP4mo3BR8PEB7C7Y2f

**Comment by blrhc** [comment]
@koen84 Paid, thanks again!

**Comment by kek-mex** [comment]
I did submit a new PR [Joystream/helpdesk#43](https://github.com/Joystream/helpdesk/pull/43).
I made two fixes to the README.md file.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ
Ps. This typo is still in the design repo: 
[Screenshot_20190829_204653](https://user-images.githubusercontent.com/50080006/63963982-c6c5b500-ca9e-11e9-8d84-c1cc6ffcdbc2.png)

**Comment by blrhc** [comment]
@kek-mex This will qualify for a $4 payout. I will confirm here once you've been paid. Thanks again!

**Comment by blrhc** [comment]
@kek-mex Paid!

**Comment by kek-mex** [comment]
I did submit a couple of new PR's.
Here is the first one, and I think that it has one reward worthy improvement: [Joystream/helpdesk#44](https://github.com/Joystream/helpdesk/pull/44).
Here is the second one, and I think that it has two reward worthy improvements: [Joystream/communications#35](https://github.com/Joystream/communications/pull/35/).
Here is the third one, and I think that it has four reward worthy improvements: [Joystream/joystream#144](https://github.com/Joystream/joystream/pull/144/).

XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by blrhc** [comment]
@kek-mex This will qualify for a $14 reward. I will confirm once the payout has been sent :)

**Comment by kek-mex** [comment]
> @kek-mex This will qualify for a $14 reward. I will confirm once the payout has been sent :)

Okay thank you once again :)

**Comment by kek-mex** [comment]
This PR was merged: [Joystream/joystream#166](https://github.com/Joystream/joystream/pull/166).
I think that 7 of these changes should be rewarded.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by blrhc** [comment]
@kek-mex This qualifies for a $14 bounty. Will confirm once sent!

**Comment by blrhc** [comment]
Sent!

**Comment by kek-mex** [comment]
> Sent!

Received thanks :)

**Comment by kek-mex** [comment]
I made a few changes to the helpdesk documentation: [Joystream/helpdesk#49](https://github.com/Joystream/helpdesk/pull/49).
I think that 9 of these changes should be rewarded.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by bwhm** [comment]
@kek-mex Payment sent!
(@blrhc)

**Comment by kek-mex** [comment]
@bwhm 
Cheers! Payment received.

Also opened a new PR: [Joystream/communications#43.](https://github.com/Joystream/communications/pull/43)
I think that 7 of these changes should be rewarded.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by blrhc** [comment]
> Joystream/communications#43.

Just checking those out now, thanks :)

**Comment by blrhc** [comment]
@kek-mex I have $14 to your XMR address to compensate for these fixes :)

**Comment by kek-mex** [comment]
This PR is ready for review: [Joystream/helpdesk#51.](https://github.com/Joystream/helpdesk/pull/51)
I think that 6 of these changes should be rewarded.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by kek-mex** [comment]
This PR was merged: [Joystream/joystream-content-system#5.](https://github.com/Joystream/joystream-content-system/pull/5)
I think that 13 of these changes should be rewarded.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by blrhc** [comment]
> This PR was merged: [Joystream/joystream-content-system#5.](https://github.com/Joystream/joystream-content-system/pull/5)
> I think that 13 of these changes should be rewarded.
> XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

Paid :)

**Comment by kek-mex** [comment]
@blrhc 
Thanks received! Here is the next one :)
[Joystream/helpdesk#51.](https://github.com/Joystream/helpdesk/pull/51)
I think that 6 of these changes should be rewarded.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

**Comment by kamalzaman** [comment]
https://github.com/Joystream/helpdesk/pull/57

Fix 9 missing links on TOC

XMR address:
46iSoXUuFnf3WBEjW3SEe7bHCjrR3geFqY1mwMNKUDBfJTATT4K72YETx4yT8FZpx2Zh8fADPZkxKSwQVNbc2vogK4AusFg

**Comment by kek-mex** [comment]
@blrhc 
Updated a lot of stuff to Joystream/joystream: [Joystream/joystream#193.](https://github.com/Joystream/joystream/pull/193)
I think that 44 of these changes should be rewarded.
XMR addy: 47XDB7X3vvBCayY6grgkAzBVyzKDmMquFiuNr4DgsujaLjq8v3j7yJ5NBruXpEZhDgVcGhMo3x8ejiX6nwxThh4aG55QdzJ

Ps. I have not been paid for the Joystream/helpdesk#51 yet ;)

**Comment by blrhc** [comment]
> [Joystream/helpdesk#57](https://github.com/Joystream/helpdesk/pull/57)
> 
> Fix 9 missing links on TOC
> 
> XMR address:
> 46iSoXUuFnf3WBEjW3SEe7bHCjrR3geFqY1mwMNKUDBfJTATT4K72YETx4yT8FZpx2Zh8fADPZkxKSwQVNbc2vogK4AusFg

Will count this as one fix if that's OK :)

**Comment by blrhc** [comment]
> Joystream/joystream#193.

Great work, will pay out in one go!

**Comment by kamalzaman** [comment]
> > [Joystream/helpdesk#57](https://github.com/Joystream/helpdesk/pull/57)
> > Fix 9 missing links on TOC
> > XMR address:
> > 46iSoXUuFnf3WBEjW3SEe7bHCjrR3geFqY1mwMNKUDBfJTATT4K72YETx4yT8FZpx2Zh8fADPZkxKSwQVNbc2vogK4AusFg
> 
> Will count this as one fix if that's OK :)

No problemo, just simple fix anyway

**Comment by blrhc** [comment]
@kamalzaman @kek-mex Paid! Thanks for your contributions.

**Comment by blrhc** [comment]
> @kamalzaman @kek-mex Paid! Thanks for your contributions.

Actually, please confirm received?

**Comment by blrhc** [comment]
> > @kamalzaman @kek-mex Paid! Thanks for your contributions.
> 
> Actually, please confirm received?

@kamalzaman Might have to wait until tomorrow, wallet empty :(

**Comment by kek-mex** [comment]
> > @kamalzaman @kek-mex Paid! Thanks for your contributions.
> 
> Actually, please confirm received?

Received. Cheers!

**Comment by blrhc** [comment]
> [Joystream/helpdesk#57](https://github.com/Joystream/helpdesk/pull/57)
> 
> Fix 9 missing links on TOC
> 
> XMR address:
> 46iSoXUuFnf3WBEjW3SEe7bHCjrR3geFqY1mwMNKUDBfJTATT4K72YETx4yT8FZpx2Zh8fADPZkxKSwQVNbc2vogK4AusFg

@kamalzaman Paid :)

**Comment by kek-mex** [comment]
@blrhc 
Few changes to the bounties repo: [Joystream/bounties#57.](https://github.com/Joystream/bounties/pull/57)
I think that 3 of these changes should be rewarded.

XMR addy: 89TtgAGERj6HCnGGfg3AffiRjTtWjYA4BCc4jhFVJ6HWFR8xdz5eSc81MNkcUivEgwcAvm4kzJZ4ciaeEqNxbAaZ5yM8AxC

**Comment by blrhc** [comment]
> @blrhc
> Few changes to the bounties repo: [Joystream/bounties#57.](https://github.com/Joystream/bounties/pull/57)
> I think that 4 of these changes should be rewarded. Please do check out my suggestion which I have added as a comment on that PR.
> 
> XMR addy: 47Y3J6LC8ibAeCLc6SZAUChhwLMDkiBHW7h2c6HHSUEZCuBBTb72Q7Mf5DzDEQhhsEiN5CktN7YzsWZYhwv4tDihAWX3NRF

Sent!

**Comment by kek-mex** [comment]
> > @blrhc
> > Few changes to the bounties repo: [Joystream/bounties#57.](https://github.com/Joystream/bounties/pull/57)
> > I think that 4 of these changes should be rewarded. Please do check out my suggestion which I have added as a comment on that PR.
> > XMR addy: 47Y3J6LC8ibAeCLc6SZAUChhwLMDkiBHW7h2c6HHSUEZCuBBTb72Q7Mf5DzDEQhhsEiN5CktN7YzsWZYhwv4tDihAWX3NRF
> 
> Sent!

Thanks a lot! Received.

**Comment by lopegor** [comment]
Hi! 

I found several links that need fixing: 
- One here: https://github.com/Joystream/founding-members/pull/18
- Seven here: https://github.com/Joystream/helpdesk/pull/91

**Comment by bwhm** [comment]
Hey @lopegor,

This repo should have been archived already, but we have the "same" bounty running [here](https://testnet.joystream.org/#/forum/threads/216)!


If the Council fails to manage these within a reasonable timeline we'll make sure to honor it regardless!
