### ISSUE TITLE
Bounty #1 - Improve networking + promotional campaign - $500*

### ISSUE THREAD

**Issue by bwhm** [Joystream/bounties#5]
Instead of writing this again, please see Joystream/joystream#39 for general information.

Although the bounty is still open, be aware that we have been in contact with one applicant, that came up with some additional ideas and research. This person have been $250 to continue looking into more details.

**Comment by mochet** [comment]
Hi, here's my proposal which has been adapted from the initial proposal on here. Let me know if you have any ideas or feedback on it.

#### Overview - Phase 1
* Campaign duration - 60 days
* Competition method - Users submit ASCII art of Joystream logo within memo field and a voting process during each cycle would determine the winner.
* Prize - VPS server for 30 days capable of running a Joystream node
	* VPS specs - Debian, 20 GB HDD, 1 GB RAM (rough estimate)
	* Financial incentive to maintain node - $200-400 ($5-10 per node per month)
* Maximum campaign winners - 40
* Maximum nodes added to network - 20 per month
* Cost of nodes - $200 (40 nodes)
* Total cost - $4-500

#### VPS vs Physical hardware distribution
I think after looking over all the pros/cons that an initial run of VPS servers would work best for this campaign, with an eventual move to hardware at a later stage.
The main benefit of this approach is that the delivery timeframe for winners is significantly shorter and cuts out numerous issues with shipping, customs and user privacy. I also think user knowledge can be focused at this stage on just Debian or a chosen OS.
I've begun contacting VPS providers to see if they can offer gift codes that can easily be sent to users and will update if there are some that can, what their pricing would be and what geographies they can currently deploy servers within.

#### Competition - Joystream logo as ASCII art
I think a really creative competition could be for users to submit an ASCII art representation of the Joystream within the Joystream memo field, something like this:
```
    _____                                  __                                                 
   |     \                                |  \                                                
    \$$$$$  ______   __    __   _______  _| $$_     ______    ______    ______   ______ ____  
      | $$ /      \ |  \  |  \ /       \|   $$ \   /      \  /      \  |      \ |      \    \ 
 __   | $$|  $$$$$$\| $$  | $$|  $$$$$$$ \$$$$$$  |  $$$$$$\|  $$$$$$\  \$$$$$$\| $$$$$$\$$$$\
|  \  | $$| $$  | $$| $$  | $$ \$$    \   | $$ __ | $$   \$$| $$    $$ /      $$| $$ | $$ | $$
| $$__| $$| $$__/ $$| $$__/ $$ _\$$$$$$\  | $$|  \| $$      | $$$$$$$$|  $$$$$$$| $$ | $$ | $$
 \$$    $$ \$$    $$ \$$    $$|       $$   \$$  $$| $$       \$$     \ \$$    $$| $$ | $$ | $$
  \$$$$$$   \$$$$$$  _\$$$$$$$ \$$$$$$$     \$$$$  \$$        \$$$$$$$  \$$$$$$$ \$$  \$$  \$$
                    |  \__| $$                                                                
                     \$$    $$                                                                
                      \$$$$$$                  
```
I've done limited experimentation with this, and as the memo field supports markdown it should be possible and will help to push users to try and be creative with on-chain features.
It would be great to have the competition winner's art showcased when starting a node via terminal, along with their on-chain username. This could be something that loads dynamically from the chain (if that is possible).

Obviously this would require using the voting system so I would be interested to hear feedback and ideas on this front (minimum participants and so on) and also require some help on how to go about implementing this from a design standpoint as it is not within my skillset (it could be given a dedicate page to showcase winners on the website or on Github)

As an extension of this it is possible to maybe have a small subset of the winners of this competition be allowed to recieve a free hardware device at a later stage--maybe a competition at the end of each week where users can vote on the best ASCII submission of that week and the winner can be awarded a very special hardware device at a later date (I'm not sure if there are legal complexities with this)

#### Payout for running node
I believe this can be monitored via telemetry or another method to get a rough idea of whether a winner actually ran a node. If anyone has ideas on how this could be monitored it would be great to hear.

#### Milestones + reporting
If chosen, I would aim to keep a weekly update of the effectiveness of the campaign. This is an example of what it would look like:

* Week 1 (January 1 - 7)
	* Applicants per 36 hour cycle:
		* 6 / 4 / 9 / 12
	* Successful vote cycle + winner decided (yes/no)
		* 1 / 1 / 1 / 1
	* Percentage of winners running nodes:
		* 100% / 90% / 90% / 80%
	* Nodes awarded during this week:
		* 5
	* Nodes nodes remaining at week end:
		* 35

**Comment by mochet** [comment]
Yes, that sounds much better in terms of timing, I think having it weekly would work well, biweekly might be a little too long. The prizes as well I think work well too. In the event of a lot of entries we can always adjust later on.
I'm currently working on understanding what is possible with VPS providers, so I think part of the timing and delivery will be based upon what they are capable of delivering, but as a starting point the weekly staging sounds like a great idea.

Here's an updated list of personal milestones that I think better explains what my role will be:

#### Milestones
* Contact at least 3 VPS Providers (2/3 are done)
	* Outcome here will ideally be a provider who allows multiple gift codes to be purchased in advance.
* Contact at least 3 hardware distributors (0/3 are done)
	* Outcome here will ideally be a distributor who will allow a certain degree of flexibility + provide a mode of shipping that includes a tracking number.
* Agree on timeframe of delivery for rewards
	* I would suggest this is capped at 60 days after competition end for winners of any hardware.
	* For servers this is dependent on what providers are capable of delivering, but should be no more than 2-3 days.
* Write legal terms and conditions that users must accept to enter competition
	* I will prepare a draft of this soon
* Write description of the competition so it can be easily shared, including highlighting what information is required from entrants as well as what communication channels will be used.
	* For VPS this should be entirely on-chain
	* For hardware, this will require an email for address etc
* Agree on naming/branding for the competition
	* "Joystream ASCII Logo Competition" works for me, open to suggestions
	* I will draft a blog post + telegram post for this once there is enough information about delivery and reward structure.
* Agree on methodology of how private data is stored and where it is sent to / stored
	* In my view, for physical rewards this should be an email address that jsgenesis controls. I can help to find a reputable hardware supplier though.
	* I'm happy to handle the VPS side of things as it should at maximum only involve an email address and name, but ideally will only require a gift code to be sent. I will have a clearer answer on this soon.
* Launch campaign
	* Deliver VPS prizes
	* Maintain report for each cycle (1 per week) including number of entrants and node uptime.

#### Deliverables
* Detailed reward structure and time-frame document, including method of capturing private data from entrants.
* Legal terms
* Promotional blog post + telegram post
* Gift code list (to remain private)
* Reporting

I have left out modification of the UI for the competition as this is not within my skillset, so it could be a seperate bounty? I suppose this would require the creation of a page within the UI that contains the terms + conditions and can show the memo field of all competition entrants, plus it would need to be tested.

**Comment by bwhm** [comment]
Looks good to me!

We can brainstorm a little internally how to best do the UI part of it, suggestions are of course welcome though! Worst case is that it's an off-chain thing for a while...

The big thing msising are some estimates on time spent for each deliverable and compensation plan for yourself.

**Comment by mochet** [comment]
Hey @bwhm here's my breakdown of expected hours + compensation plan for consideration:

#### Breakdown
* Research and initial contact with VPS companies
	* 7.5-10 hours
	* $300

* Testing memo field across platforms + writing instructions for competition + screenshots + examples of ASCII art + basic UI proposal / sketch / T+Cs
	* 5-10 hours
	* $400

* Writing blog post + marketing material
	* 2-3 hours
	* $100

* Sending gift codes / maintaining competition / writing weekly reports
	* $20 per vote cycle/week
		* This I think will change depending on how involved the process actually is.
	* If I'm not available for some week, then this role could be given to another person

* Research and initial contact with hardware companies (this I think would happen at a later stage)
	* 4-5 hours
	* $200

**Comment by bwhm** [comment]
Looks good @mochet!

Let me know once you have made a decision, and secured a VPS provider. Then we will pay out the second milestone!

**Comment by mochet** [comment]
@bwhm here's a breakdown of providers contacted so far, and I think we've reached a point where we have a provider who would work at this initial stage. Later on we could expand to multiple providers depending on scale.

I think the best provider I've contacted so far is Upcloud, it just has to be agreed on whether we do some form of branding placement for them to build a relationship. I've included some thoughts on that below.
They offer Finland/Germany/Netherlands/Singapore/United Kingdom/USA as options for servers and I think that a 1 GB, 1 CPU VPS with 1 TB of bandwidth will likely be enough for now to host a node.

* VPSie
	* Couldn't really do gift codes. Still an option in the future potentially.
* Vultr
	* Couldn't really do gift codes. Still an option in the future potentially.
* VPSCheap.net
	* Could do gift codes, so still an option.
* Linode
	* Awaiting response.
* Upcloud
	* Seems like the best option so far
	* Seems like they are happy to allow us a way to do a give away of accounts to users: _For the accounts, either you provide us the info (Names + Email Addresses) and we create the accounts for you and add the credits in them or we can just create random 30/40 accounts with random credentials and you can suggest the winners to change their details later on after logging into their accounts. _
	* Offered a 50% discount: _Regarding the pricing, we would like to offer you a 50% discount and if you could give away some of our cool swag pack to the winners (Coasters, mugs, stickers, mouse pads etc) to the developers and may be some visibility also on your pages presenting us as co-sponsors, should be great :) _
	* I don't think I'll take them up on the offer of branding/promo stuff because I think it would be too complex for users at this stage + it would require them to give up more private data. 
	* We could just mention they're the chosen provider in the documentation or maybe give a small logo placement in exchange for nothing (purely to build trust/relationship in the event a lot more VPS are needed at some point in the future, I think its a good idea to build relationships with service providers and since they are not a cryptocurrency specific provider, it would help to solidify Joystream as not being reliant on just the crypto ecosystem)
	* If anything, at a later stage it might be possible to build relationships with service providers into a way to subsidize the cost of servers in exchange for mentioning their branding in a small way, which would benefit the project + community + providers.

**Comment by mochet** [comment]
It looks like the testnet is about 10 GB in size + some nodes appear to be using more RAM than others. Considering the timeline of the competition is about 3+ months we might need to look at what resources would work best to last this long.

So I'll wait a little for Acropolis to launch and then we can discuss what might work for this to work well.

**Comment by mochet** [comment]
Just had a meeting with @bwhm and a few points:

- Competition will move from using memo field to using the on-chain forum. This would make managing and moderating it a lot easier and contribute to and hopefully result in increased forum engagement by users.
- Still have to choose between how users vote, but token voting will probably be easiest way for now.
- Investigating possibility of creating infographics for each round of competition. If this works well can be used on social media channels to demonstrate user contributions to platform + number of votes over time and hopefully drive further engagement on platform.
- Storage size of chain is currently around 12 GB, if competition runs for 3 months+ then we will probably need to use larger size nodes than previously estimated. Chain seems to take a bit more storage until its completely synchronized as well.
- Showing ASCII art loaded from chain into nodes would likely introduce too many issues for now, so that part will be ignored for the time being.

**Comment by bwhm** [comment]
Thanks for the summary!

Will add that we have settled on a VPS provider, so that milestone is reached. Payout will be made today.

**Comment by blrhc** [comment]
Closing this bounty for now, but may be re-opened at some point in the future.
